import { StyleSheet } from 'react-native';
import { FLEX, SHADOW_OFFSET, DIMENSIONS, TEXT_ALIGN_VERTICAL } from '../../../../shared/constants';
import { mobileTypography, designTokens, layoutConstants } from '../../../theme';

export const styles = StyleSheet.create({
  container: { flex: FLEX.ONE, backgroundColor: designTokens.colors.backgroundSecondary },
  content: { flex: FLEX.ONE },
  emptyState: {
    alignItems: layoutConstants.alignItems.center,
    justifyContent: layoutConstants.justifyContent.center,
    paddingVertical: designTokens.spacing['7xl'],
    paddingHorizontal: designTokens.spacing['4xl'],
  },
  emptyText: {
    ...mobileTypography.heading3,
    color: designTokens.colors.textSecondary,
    marginTop: designTokens.spacing.lg,
  },
  emptySubtext: {
    ...mobileTypography.bodySmall,
    color: designTokens.colors.textTertiary,
    textAlign: layoutConstants.textAlign.center,
    marginTop: designTokens.spacing.sm,
  },
  footer: {
    padding: designTokens.spacing.xl,
    backgroundColor: designTokens.colors.backgroundPrimary,
    borderTopWidth: designTokens.borderWidth.thin,
    borderTopColor: designTokens.colors.borderLight,
  },
  saveButton: {
    flexDirection: layoutConstants.flexDirection.row,
    alignItems: layoutConstants.alignItems.center,
    justifyContent: layoutConstants.justifyContent.center,
    backgroundColor: designTokens.colors.primary,
    paddingVertical: designTokens.spacing.md,
    borderRadius: designTokens.borderRadius.xl,
    gap: designTokens.spacing.md,
  },
  saveButtonText: { ...mobileTypography.button, color: designTokens.colors.textInverse },
  footerButtons: { flexDirection: layoutConstants.flexDirection.row, gap: designTokens.spacing.md },
  editButton: {
    flexDirection: layoutConstants.flexDirection.row,
    alignItems: layoutConstants.alignItems.center,
    justifyContent: layoutConstants.justifyContent.center,
    backgroundColor: designTokens.colors.backgroundSecondary,
    paddingVertical: designTokens.spacing.md,
    paddingHorizontal: designTokens.spacing.xl,
    borderRadius: designTokens.borderRadius.xl,
    gap: designTokens.spacing.sm,
  },
  editButtonText: { ...mobileTypography.button, color: designTokens.colors.primary },
  shareButton: {
    flexDirection: layoutConstants.flexDirection.row,
    alignItems: layoutConstants.alignItems.center,
    justifyContent: layoutConstants.justifyContent.center,
    backgroundColor: designTokens.colors.success,
    paddingVertical: designTokens.spacing.md,
    paddingHorizontal: designTokens.spacing.xl,
    borderRadius: designTokens.borderRadius.xl,
    gap: designTokens.spacing.md,
    flex: FLEX.ONE,
  },
  shareButtonText: { ...mobileTypography.button, color: designTokens.colors.textInverse },
});

export const meetingInfoStyles = StyleSheet.create({
  section: {
    backgroundColor: designTokens.colors.backgroundPrimary,
    paddingHorizontal: designTokens.spacing.xl,
    paddingVertical: designTokens.spacing.lg,
    borderBottomWidth: designTokens.borderWidth.thin,
    borderBottomColor: designTokens.colors.borderLight,
    gap: designTokens.spacing.md,
  },
  row: {
    flexDirection: layoutConstants.flexDirection.row,
    alignItems: layoutConstants.alignItems.center,
    gap: designTokens.spacing.md,
  },
  label: { ...mobileTypography.labelBold, color: designTokens.colors.textSecondary },
  date: {
    ...mobileTypography.bodyMediumBold,
    color: designTokens.colors.textPrimary,
    flex: FLEX.ONE,
  },
  quickDateButtons: {
    flexDirection: layoutConstants.flexDirection.row,
    gap: designTokens.spacing.md,
  },
  quickDateButton: {
    flex: FLEX.ONE,
    backgroundColor: designTokens.colors.primaryLight,
    paddingVertical: designTokens.spacing.md,
    paddingHorizontal: designTokens.spacing.lg,
    borderRadius: designTokens.borderRadius.md,
    alignItems: layoutConstants.alignItems.center,
  },
  quickDateText: { ...mobileTypography.labelBold, color: designTokens.colors.primary },
  titleInput: {
    ...mobileTypography.bodyLarge,
    borderWidth: designTokens.borderWidth.thin,
    borderColor: designTokens.colors.borderLight,
    borderRadius: designTokens.borderRadius.md,
    paddingHorizontal: designTokens.spacing.md,
    paddingVertical: designTokens.spacing.md,
    backgroundColor: designTokens.colors.inputBackground,
  },
  totalTimeBanner: {
    flexDirection: layoutConstants.flexDirection.row,
    alignItems: layoutConstants.alignItems.center,
    backgroundColor: designTokens.colors.primaryLight,
    paddingHorizontal: designTokens.spacing.xl,
    paddingVertical: designTokens.spacing.md,
    gap: designTokens.spacing.md,
  },
  totalTimeText: { ...mobileTypography.bodySmall, color: designTokens.colors.primary },
  totalTimeBold: { ...mobileTypography.bodyMediumBold, color: designTokens.colors.primary },
});

export const agendaCardStyles = StyleSheet.create({
  card: {
    flexDirection: layoutConstants.flexDirection.row,
    backgroundColor: designTokens.colors.backgroundPrimary,
    padding: designTokens.spacing.lg,
    marginHorizontal: designTokens.spacing.lg,
    marginTop: designTokens.spacing.md,
    borderRadius: designTokens.borderRadius.lg,
    shadowColor: designTokens.colors.textPrimary,
    shadowOffset: SHADOW_OFFSET.MD,
    shadowOpacity: designTokens.shadows.sm.shadowOpacity,
    shadowRadius: designTokens.shadows.sm.shadowRadius,
    elevation: designTokens.shadows.sm.elevation,
  },
  orderBadge: {
    width: DIMENSIONS.SIZE.ORDER_BADGE,
    height: DIMENSIONS.SIZE.ORDER_BADGE,
    borderRadius: designTokens.borderRadius.xl,
    backgroundColor: designTokens.colors.primary,
    justifyContent: layoutConstants.justifyContent.center,
    alignItems: layoutConstants.alignItems.center,
    marginRight: designTokens.spacing.md,
  },
  orderText: { ...mobileTypography.labelBold, color: designTokens.colors.textInverse },
  content: { flex: FLEX.ONE },
  header: {
    flexDirection: layoutConstants.flexDirection.row,
    justifyContent: layoutConstants.justifyContent.spaceBetween,
    alignItems: layoutConstants.alignItems.flexStart,
    marginBottom: designTokens.spacing.sm,
    gap: designTokens.spacing.sm,
  },
  title: { ...mobileTypography.bodyMediumBold, flex: FLEX.ONE },
  timeChip: {
    flexDirection: layoutConstants.flexDirection.row,
    alignItems: layoutConstants.alignItems.center,
    backgroundColor: designTokens.colors.backgroundSecondary,
    paddingHorizontal: designTokens.spacing.sm,
    paddingVertical: designTokens.spacing.xs,
    borderRadius: designTokens.borderRadius.lg,
    gap: designTokens.spacing.xs,
  },
  timeText: {
    ...mobileTypography.caption,
    color: designTokens.colors.textSecondary,
    fontWeight: designTokens.fontWeight.semibold,
  },
  description: {
    ...mobileTypography.bodySmall,
    color: designTokens.colors.textSecondary,
    marginBottom: designTokens.spacing.sm,
  },
  responsibleSection: { marginTop: designTokens.spacing.sm },
  memberChip: {
    flexDirection: layoutConstants.flexDirection.row,
    alignItems: layoutConstants.alignItems.center,
    backgroundColor: designTokens.colors.primaryLight,
    paddingVertical: designTokens.spacing.sm,
    paddingHorizontal: designTokens.spacing.md,
    borderRadius: designTokens.borderRadius.xl,
    alignSelf: layoutConstants.alignSelf.flexStart,
    gap: designTokens.spacing.sm,
  },
  memberName: {
    ...mobileTypography.label,
    color: designTokens.colors.primary,
    fontWeight: designTokens.fontWeight.semibold,
    flex: FLEX.ONE,
  },
  actions: { marginLeft: designTokens.spacing.md, gap: designTokens.spacing.sm },
  moveButtons: { gap: designTokens.spacing.xs },
  moveButton: { padding: designTokens.spacing.xs },
  moveButtonDisabled: { opacity: designTokens.opacity.low },
  actionButton: { padding: designTokens.spacing.xs },
});

export const assignButtonStyles = StyleSheet.create({
  button: {
    flexDirection: layoutConstants.flexDirection.row,
    alignItems: layoutConstants.alignItems.center,
    paddingVertical: designTokens.spacing.sm,
    paddingHorizontal: designTokens.spacing.md,
    borderRadius: designTokens.borderRadius.md,
    borderWidth: designTokens.borderWidth.thin,
    borderColor: designTokens.colors.primary,
    alignSelf: layoutConstants.alignSelf.flexStart,
    gap: designTokens.spacing.sm,
  },
  text: {
    ...mobileTypography.label,
    color: designTokens.colors.primary,
    fontWeight: designTokens.fontWeight.semibold,
  },
});

export const modalStyles = StyleSheet.create({
  overlay: {
    flex: FLEX.ONE,
    backgroundColor: designTokens.overlay.darkMedium,
    justifyContent: layoutConstants.justifyContent.flexEnd,
  },
  content: {
    backgroundColor: designTokens.colors.backgroundPrimary,
    borderTopLeftRadius: designTokens.borderRadius.xl,
    borderTopRightRadius: designTokens.borderRadius.xl,
  },
  header: {
    flexDirection: layoutConstants.flexDirection.row,
    justifyContent: layoutConstants.justifyContent.spaceBetween,
    alignItems: layoutConstants.alignItems.center,
    padding: designTokens.spacing.xl,
    borderBottomWidth: designTokens.borderWidth.thin,
    borderBottomColor: designTokens.colors.borderLight,
  },
  title: { ...mobileTypography.heading2 },
  body: { padding: designTokens.spacing.xl },
  inputLabel: {
    ...mobileTypography.labelBold,
    color: designTokens.colors.textPrimary,
    marginBottom: designTokens.spacing.sm,
    marginTop: designTokens.spacing.md,
  },
  input: {
    ...mobileTypography.bodyLarge,
    borderWidth: designTokens.borderWidth.thin,
    borderColor: designTokens.colors.borderLight,
    borderRadius: designTokens.borderRadius.md,
    paddingHorizontal: designTokens.spacing.md,
    paddingVertical: designTokens.spacing.md,
    backgroundColor: designTokens.colors.inputBackground,
  },
  textArea: {
    minHeight: DIMENSIONS.MIN_HEIGHT.TEXTAREA,
    textAlignVertical: TEXT_ALIGN_VERTICAL.TOP,
  },
  footer: {
    flexDirection: layoutConstants.flexDirection.row,
    gap: designTokens.spacing.md,
    padding: designTokens.spacing.xl,
    borderTopWidth: designTokens.borderWidth.thin,
    borderTopColor: designTokens.colors.borderLight,
  },
  button: {
    flex: FLEX.ONE,
    paddingVertical: designTokens.spacing.md,
    borderRadius: designTokens.borderRadius.md,
    alignItems: layoutConstants.alignItems.center,
  },
  cancelButton: { backgroundColor: designTokens.colors.backgroundSecondary },
  cancelButtonText: { ...mobileTypography.button, color: designTokens.colors.textSecondary },
  confirmButton: { backgroundColor: designTokens.colors.primary },
  confirmButtonText: { ...mobileTypography.button, color: designTokens.colors.textInverse },
  memberOption: {
    flexDirection: layoutConstants.flexDirection.row,
    alignItems: layoutConstants.alignItems.center,
    padding: designTokens.spacing.md,
    borderRadius: designTokens.borderRadius.md,
    backgroundColor: designTokens.colors.inputBackground,
    marginBottom: designTokens.spacing.sm,
  },
  memberAvatar: {
    width: designTokens.componentSizes.iconContainer.md,
    height: designTokens.componentSizes.iconContainer.md,
    borderRadius: designTokens.borderRadius['2xl'],
    backgroundColor: designTokens.colors.primary,
    justifyContent: layoutConstants.justifyContent.center,
    alignItems: layoutConstants.alignItems.center,
    marginRight: designTokens.spacing.md,
  },
  memberAvatarText: { ...mobileTypography.bodyMediumBold, color: designTokens.colors.textInverse },
  memberInfo: { flex: FLEX.ONE },
  memberOptionName: { ...mobileTypography.bodyMediumBold },
  memberOptionEmail: { ...mobileTypography.caption, color: designTokens.colors.textSecondary },
  noMembersText: {
    ...mobileTypography.bodySmall,
    color: designTokens.colors.textTertiary,
    textAlign: layoutConstants.textAlign.center,
    paddingVertical: designTokens.spacing['4xl'],
  },
});

export const shareModalStyles = StyleSheet.create({
  content: {
    backgroundColor: designTokens.colors.backgroundPrimary,
    borderRadius: designTokens.borderRadius['2xl'],
    padding: designTokens.spacing.xxl,
    alignSelf: layoutConstants.alignSelf.center,
  },
  header: { alignItems: layoutConstants.alignItems.center, marginBottom: designTokens.spacing.xxl },
  iconContainer: {
    width: DIMENSIONS.SIZE.SHARE_ICON_LARGE,
    height: DIMENSIONS.SIZE.SHARE_ICON_LARGE,
    borderRadius: designTokens.borderRadius.full,
    backgroundColor: designTokens.colors.primaryLight,
    justifyContent: layoutConstants.justifyContent.center,
    alignItems: layoutConstants.alignItems.center,
    marginBottom: designTokens.spacing.lg,
  },
  title: {
    ...mobileTypography.heading2,
    textAlign: layoutConstants.textAlign.center,
    marginBottom: designTokens.spacing.sm,
  },
  subtitle: {
    ...mobileTypography.bodySmall,
    color: designTokens.colors.textSecondary,
    textAlign: layoutConstants.textAlign.center,
  },
  info: {
    backgroundColor: designTokens.colors.inputBackground,
    borderRadius: designTokens.borderRadius.lg,
    padding: designTokens.spacing.lg,
    gap: designTokens.spacing.lg,
    marginBottom: designTokens.spacing.xxl,
  },
  infoRow: {
    flexDirection: layoutConstants.flexDirection.row,
    alignItems: layoutConstants.alignItems.center,
    gap: designTokens.spacing.md,
  },
  infoText: { flex: FLEX.ONE },
  infoLabel: {
    ...mobileTypography.label,
    color: designTokens.colors.textSecondary,
    marginBottom: designTokens.spacing.xs,
  },
  infoValue: { ...mobileTypography.bodyMediumBold, color: designTokens.colors.textPrimary },
  actions: { flexDirection: layoutConstants.flexDirection.row, gap: designTokens.spacing.md },
  confirmButton: {
    flex: FLEX.ONEAndHalf,
    flexDirection: layoutConstants.flexDirection.row,
    gap: designTokens.spacing.sm,
    backgroundColor: designTokens.colors.success,
  },
});
