import { StyleSheet } from 'react-native';
import { FLEX, DIMENSIONS } from '../../../../shared/constants';
import { MATH } from '../../../../shared/constants/numbers';
import { mobileFontSizes, designTokens, layoutConstants } from '../../../theme';

export const modalStyles = StyleSheet.create({
  overlay: {
    flex: FLEX.ONE,
    backgroundColor: designTokens.overlay.darkMedium,
    justifyContent: layoutConstants.justifyContent.center,
    alignItems: layoutConstants.alignItems.center,
    padding: designTokens.spacing.xl,
  },
  content: {
    backgroundColor: designTokens.colors.backgroundPrimary,
    borderRadius: designTokens.borderRadius['2xl'],
    ...designTokens.shadows['2xl'],
  },
  header: {
    flexDirection: layoutConstants.flexDirection.row,
    justifyContent: layoutConstants.justifyContent.spaceBetween,
    alignItems: layoutConstants.alignItems.center,
    padding: designTokens.spacing.xl,
    borderBottomWidth: designTokens.borderWidth.thin,
    borderBottomColor: designTokens.colors.borderLight,
  },
  title: {
    fontSize: mobileFontSizes['2xl'],
    fontWeight: designTokens.fontWeight.bold,
    color: designTokens.colors.textPrimary,
  },
  closeButton: { padding: designTokens.spacing.xs },
  body: { padding: designTokens.spacing.xl, maxHeight: DIMENSIONS.MAX_HEIGHT.MODAL_BODY_LARGE },
  inputGroup: { marginBottom: designTokens.spacing.xxl },
  label: {
    fontSize: mobileFontSizes.md,
    fontWeight: designTokens.fontWeight.semibold,
    color: designTokens.colors.textPrimary,
    marginBottom: designTokens.spacing.sm,
  },
  input: {
    backgroundColor: designTokens.colors.backgroundSecondary,
    borderWidth: designTokens.borderWidth.thin,
    borderColor: designTokens.colors.borderLight,
    borderRadius: designTokens.borderRadius.lg,
    padding: designTokens.spacing.md + designTokens.spacing.xxs,
    fontSize: mobileFontSizes.lg,
    color: designTokens.colors.textPrimary,
  },
  hint: {
    fontSize: mobileFontSizes.xs,
    color: designTokens.colors.textTertiary,
    marginTop: designTokens.spacing.xs + designTokens.spacing.xxs,
  },
  applyToContainer: {
    flexDirection: layoutConstants.flexDirection.row,
    gap: designTokens.spacing.md,
  },
  applyToOption: {
    flex: FLEX.ONE,
    flexDirection: layoutConstants.flexDirection.row,
    alignItems: layoutConstants.alignItems.center,
    justifyContent: layoutConstants.justifyContent.center,
    gap: designTokens.spacing.sm,
    paddingVertical: designTokens.spacing.md + designTokens.spacing.xxs,
    paddingHorizontal: designTokens.spacing.md,
    backgroundColor: designTokens.colors.backgroundSecondary,
    borderWidth: designTokens.borderWidth.medium,
    borderColor: designTokens.colors.borderLight,
    borderRadius: designTokens.borderRadius.lg,
  },
  applyToOptionActive: {
    backgroundColor: designTokens.colors.primaryAlpha20,
    borderColor: designTokens.colors.primary,
  },
  applyToText: {
    fontSize: mobileFontSizes.sm,
    fontWeight: designTokens.fontWeight.semibold,
    color: designTokens.colors.textSecondary,
  },
  applyToTextActive: { color: designTokens.colors.textPrimary },
  memberSelectionContainer: {
    marginTop: designTokens.spacing.lg,
    backgroundColor: designTokens.colors.backgroundSecondary,
    borderRadius: designTokens.borderRadius.lg,
    padding: designTokens.spacing.md,
    maxHeight: designTokens.spacing['8xl'] * MATH.HALF + designTokens.spacing['6xl'],
  },
  memberSelectionHeader: {
    flexDirection: layoutConstants.flexDirection.row,
    justifyContent: layoutConstants.justifyContent.spaceBetween,
    alignItems: layoutConstants.alignItems.center,
    marginBottom: designTokens.spacing.md,
    paddingBottom: designTokens.spacing.md,
    borderBottomWidth: designTokens.borderWidth.thin,
    borderBottomColor: designTokens.colors.borderLight,
  },
  memberSelectionTitle: {
    fontSize: mobileFontSizes.sm,
    fontWeight: designTokens.fontWeight.semibold,
    color: designTokens.colors.textPrimary,
  },
  selectAllButton: {
    paddingVertical: designTokens.spacing.xs,
    paddingHorizontal: designTokens.spacing.md,
    backgroundColor: designTokens.colors.infoAlpha20,
    borderRadius: designTokens.borderRadius.sm,
  },
  selectAllText: {
    fontSize: mobileFontSizes.xs,
    fontWeight: designTokens.fontWeight.semibold,
    color: designTokens.colors.textPrimary,
  },
  membersList: { gap: designTokens.spacing.sm },
  memberItem: {
    flexDirection: layoutConstants.flexDirection.row,
    alignItems: layoutConstants.alignItems.center,
    justifyContent: layoutConstants.justifyContent.spaceBetween,
    padding: designTokens.spacing.md,
    backgroundColor: designTokens.colors.backgroundPrimary,
    borderRadius: designTokens.borderRadius.lg,
    borderWidth: designTokens.borderWidth.medium,
    borderColor: designTokens.colors.borderLight,
  },
  memberItemSelected: {
    backgroundColor: designTokens.colors.primaryAlpha20,
    borderColor: designTokens.colors.primary,
  },
  memberItemLeft: {
    flexDirection: layoutConstants.flexDirection.row,
    alignItems: layoutConstants.alignItems.center,
    gap: designTokens.spacing.md,
    flex: FLEX.ONE,
  },
  checkbox: {
    width: designTokens.spacing.xxl,
    height: designTokens.spacing.xxl,
    borderRadius: designTokens.borderRadius.sm,
    borderWidth: designTokens.borderWidth.medium,
    borderColor: designTokens.colors.borderLight,
    justifyContent: layoutConstants.justifyContent.center,
    alignItems: layoutConstants.alignItems.center,
    backgroundColor: designTokens.colors.backgroundPrimary,
  },
  checkboxSelected: {
    backgroundColor: designTokens.colors.primary,
    borderColor: designTokens.colors.primary,
  },
  memberItemInfo: { flex: FLEX.ONE },
  memberItemName: {
    fontSize: mobileFontSizes.md,
    fontWeight: designTokens.fontWeight.semibold,
    color: designTokens.colors.textPrimary,
    marginBottom: designTokens.spacing.xxs,
  },
  memberItemEmail: { fontSize: mobileFontSizes.xs, color: designTokens.colors.textSecondary },
  footer: {
    flexDirection: layoutConstants.flexDirection.row,
    gap: designTokens.spacing.md,
    padding: designTokens.spacing.xl,
    borderTopWidth: designTokens.borderWidth.thin,
    borderTopColor: designTokens.colors.borderLight,
  },
  cancelButton: {
    flex: FLEX.ONE,
    paddingVertical: designTokens.spacing.md + designTokens.spacing.xxs,
    borderRadius: designTokens.borderRadius.lg,
    borderWidth: designTokens.borderWidth.medium,
    borderColor: designTokens.colors.borderLight,
    alignItems: layoutConstants.alignItems.center,
    justifyContent: layoutConstants.justifyContent.center,
  },
  cancelText: {
    fontSize: mobileFontSizes.lg,
    fontWeight: designTokens.fontWeight.semibold,
    color: designTokens.colors.textSecondary,
  },
  createButton: {
    flex: FLEX.ONE,
    flexDirection: layoutConstants.flexDirection.row,
    alignItems: layoutConstants.alignItems.center,
    justifyContent: layoutConstants.justifyContent.center,
    gap: designTokens.spacing.sm,
    paddingVertical: designTokens.spacing.md + designTokens.spacing.xxs,
    borderRadius: designTokens.borderRadius.lg,
    backgroundColor: designTokens.colors.primary,
    ...designTokens.shadows.sm,
  },
  createText: {
    fontSize: mobileFontSizes.lg,
    fontWeight: designTokens.fontWeight.semibold,
    color: designTokens.colors.white,
  },
});
