import { StyleSheet } from 'react-native';
import { mobileFontSizes, designTokens, layoutConstants } from '../../../shared/theme';
import { FLEX, SHADOW_OFFSET } from '../../../shared/constants';
import { MATH } from '../../../shared/constants/http';

export const styles = StyleSheet.create({
  container: { flex: FLEX.ONE, backgroundColor: designTokens.colors.backgroundSecondary },
  loadingContainer: {
    flex: FLEX.ONE,
    justifyContent: layoutConstants.justifyContent.center,
    alignItems: layoutConstants.alignItems.center,
    backgroundColor: designTokens.colors.backgroundSecondary,
  },
  loadingText: {
    marginTop: designTokens.spacing.lg,
    fontSize: mobileFontSizes.lg,
    color: designTokens.colors.textSecondary,
  },
  header: {
    backgroundColor: designTokens.colors.primary,
    padding: designTokens.spacing.xl,
    paddingTop: designTokens.spacing['6xl'],
    paddingBottom: designTokens.spacing.xxl,
  },
  headerTitle: {
    fontSize: mobileFontSizes['4xl'],
    fontWeight: designTokens.fontWeight.bold,
    color: designTokens.colors.white,
    marginBottom: designTokens.spacing.xs,
  },
  headerSubtitle: { fontSize: mobileFontSizes.sm, color: designTokens.overlay.lightStrong },
  tabContent: { flex: FLEX.ONE },
  section: { padding: designTokens.spacing.lg },
});

export const tabStyles = StyleSheet.create({
  tabs: {
    flexDirection: layoutConstants.flexDirection.row,
    backgroundColor: designTokens.colors.backgroundPrimary,
    borderBottomWidth: designTokens.borderWidth.thin,
    borderBottomColor: designTokens.colors.borderLight,
    elevation: designTokens.shadows.sm.elevation,
    shadowColor: designTokens.colors.textPrimary,
    shadowOffset: SHADOW_OFFSET.MD,
    shadowOpacity: designTokens.shadows.sm.shadowOpacity,
    shadowRadius: designTokens.shadows.sm.shadowRadius,
  },
  tab: {
    flex: FLEX.ONE,
    flexDirection: layoutConstants.flexDirection.row,
    alignItems: layoutConstants.alignItems.center,
    justifyContent: layoutConstants.justifyContent.center,
    paddingVertical: designTokens.spacing.lg,
    gap: designTokens.spacing.sm,
    borderBottomWidth: designTokens.borderWidth.thick,
    borderBottomColor: designTokens.colors.transparent,
  },
  tabActive: { borderBottomColor: designTokens.colors.primary },
  tabText: {
    fontSize: mobileFontSizes.sm,
    color: designTokens.colors.textSecondary,
    fontWeight: designTokens.fontWeight.medium,
  },
  tabTextActive: {
    color: designTokens.colors.primary,
    fontWeight: designTokens.fontWeight.semibold,
  },
});

export const settingsStyles = StyleSheet.create({
  infoCard: {
    flexDirection: layoutConstants.flexDirection.row,
    backgroundColor: designTokens.colors.primaryLight,
    borderRadius: designTokens.borderRadius.lg,
    padding: designTokens.spacing.lg,
    marginBottom: designTokens.spacing.xl,
    borderLeftWidth: designTokens.borderWidth.heavy,
    borderLeftColor: designTokens.colors.primary,
  },
  infoIconContainer: { marginRight: designTokens.spacing.md, marginTop: designTokens.spacing.xxs },
  infoTextContainer: { flex: FLEX.ONE },
  infoTitle: {
    fontSize: mobileFontSizes.md,
    fontWeight: designTokens.fontWeight.semibold,
    color: designTokens.colors.primary,
    marginBottom: designTokens.spacing.xs,
  },
  infoText: {
    fontSize: mobileFontSizes.xs,
    color: designTokens.colors.primary,
    lineHeight: designTokens.spacing.lg + designTokens.spacing.xxs,
  },
  settingCard: {
    backgroundColor: designTokens.colors.backgroundPrimary,
    borderRadius: designTokens.borderRadius.lg,
    padding: designTokens.spacing.lg,
    marginBottom: designTokens.spacing.lg,
    ...designTokens.shadows.sm,
  },
  settingRow: {
    flexDirection: layoutConstants.flexDirection.row,
    justifyContent: layoutConstants.justifyContent.spaceBetween,
    alignItems: layoutConstants.alignItems.center,
  },
  settingLabelContainer: { flex: FLEX.ONE, marginRight: designTokens.spacing.lg },
  settingLabel: {
    fontSize: mobileFontSizes.lg,
    fontWeight: designTokens.fontWeight.semibold,
    color: designTokens.colors.textPrimary,
    marginBottom: designTokens.spacing.xs,
  },
  settingSubtext: { fontSize: mobileFontSizes.xs, color: designTokens.colors.textSecondary },
  inputCard: {
    backgroundColor: designTokens.colors.backgroundPrimary,
    borderRadius: designTokens.borderRadius.lg,
    padding: designTokens.spacing.lg,
    marginBottom: designTokens.spacing.lg,
    ...designTokens.shadows.sm,
  },
  inputLabel: {
    fontSize: mobileFontSizes.md,
    fontWeight: designTokens.fontWeight.semibold,
    color: designTokens.colors.textPrimary,
    marginBottom: designTokens.spacing.xs,
  },
  inputSubtext: {
    fontSize: mobileFontSizes.xs,
    color: designTokens.colors.textSecondary,
    marginBottom: designTokens.spacing.md,
  },
  amountRow: { flexDirection: layoutConstants.flexDirection.row, gap: designTokens.spacing.md },
  amountInputWrapper: { flex: FLEX.ONE },
  currencyInputWrapper: { width: designTokens.spacing['8xl'] + designTokens.spacing.xs },
  amountInputContainer: {
    flex: FLEX.ONE,
    flexDirection: layoutConstants.flexDirection.row,
    alignItems: layoutConstants.alignItems.center,
    backgroundColor: designTokens.colors.backgroundSecondary,
    borderWidth: designTokens.borderWidth.thin,
    borderColor: designTokens.colors.borderLight,
    borderRadius: designTokens.borderRadius.lg,
    paddingHorizontal: designTokens.spacing.lg,
  },
  currencySymbol: {
    fontSize: mobileFontSizes.xl,
    fontWeight: designTokens.fontWeight.semibold,
    color: designTokens.colors.primary,
    marginRight: designTokens.spacing.sm,
  },
  amountInput: {
    flex: FLEX.ONE,
    padding: designTokens.spacing.md + designTokens.spacing.xxs,
    fontSize: mobileFontSizes.lg,
    fontWeight: designTokens.fontWeight.semibold,
    color: designTokens.colors.textPrimary,
  },
  currencyInputContainer: {
    width: designTokens.spacing['8xl'] + designTokens.spacing.xs,
    backgroundColor: designTokens.colors.backgroundSecondary,
    borderWidth: designTokens.borderWidth.thin,
    borderColor: designTokens.colors.borderLight,
    borderRadius: designTokens.borderRadius.lg,
  },
  currencyInput: {
    padding: designTokens.spacing.md + designTokens.spacing.xxs,
    fontSize: mobileFontSizes.lg,
    fontWeight: designTokens.fontWeight.semibold,
    color: designTokens.colors.textPrimary,
    textAlign: layoutConstants.textAlign.center,
  },
  monthHeaderRow: {
    flexDirection: layoutConstants.flexDirection.row,
    justifyContent: layoutConstants.justifyContent.spaceBetween,
    alignItems: layoutConstants.alignItems.flexStart,
    marginBottom: designTokens.spacing.lg,
  },
  monthActions: { flexDirection: layoutConstants.flexDirection.row, gap: designTokens.spacing.md },
  monthActionBtn: {
    paddingVertical: designTokens.spacing.xs + designTokens.spacing.xxs,
    paddingHorizontal: designTokens.spacing.md,
    backgroundColor: designTokens.colors.borderLight,
    borderRadius: designTokens.borderRadius.sm,
  },
  monthActionText: {
    fontSize: mobileFontSizes.xs,
    color: designTokens.colors.primary,
    fontWeight: designTokens.fontWeight.semibold,
  },
  monthGrid: {
    flexDirection: layoutConstants.flexDirection.row,
    flexWrap: layoutConstants.flexWrap.wrap,
    gap: designTokens.spacing.sm + designTokens.spacing.xxs,
  },
  monthChip: {
    paddingVertical: designTokens.spacing.sm + designTokens.spacing.xxs,
    paddingHorizontal: designTokens.spacing.lg + designTokens.spacing.xxs,
    borderRadius: designTokens.borderRadius.md,
    backgroundColor: designTokens.colors.backgroundSecondary,
    borderWidth: designTokens.borderWidth.medium,
    borderColor: designTokens.colors.borderLight,
    minWidth: designTokens.spacing['6xl'] + designTokens.spacing.xs,
    alignItems: layoutConstants.alignItems.center,
  },
  monthChipSelected: {
    backgroundColor: designTokens.colors.primary,
    borderColor: designTokens.colors.primary,
  },
  monthChipText: {
    fontSize: mobileFontSizes.xs,
    color: designTokens.colors.textSecondary,
    fontWeight: designTokens.fontWeight.medium,
  },
  monthChipTextSelected: {
    color: designTokens.colors.white,
    fontWeight: designTokens.fontWeight.semibold,
  },
  actionButtonsContainer: {
    gap: designTokens.spacing.md,
    marginTop: designTokens.spacing.sm,
  },
  primaryButton: {
    backgroundColor: designTokens.colors.primary,
    flexDirection: layoutConstants.flexDirection.row,
    alignItems: layoutConstants.alignItems.center,
    justifyContent: layoutConstants.justifyContent.center,
    paddingVertical: designTokens.spacing.lg,
    borderRadius: designTokens.borderRadius.lg,
    gap: designTokens.spacing.sm + designTokens.spacing.xxs,
    ...designTokens.shadows.md,
  },
  primaryButtonText: {
    color: designTokens.colors.white,
    fontSize: mobileFontSizes.lg,
    fontWeight: designTokens.fontWeight.semibold,
  },
  secondaryButton: {
    backgroundColor: designTokens.colors.backgroundPrimary,
    flexDirection: layoutConstants.flexDirection.row,
    alignItems: layoutConstants.alignItems.center,
    justifyContent: layoutConstants.justifyContent.center,
    paddingVertical: designTokens.spacing.lg,
    borderRadius: designTokens.borderRadius.lg,
    gap: designTokens.spacing.sm + designTokens.spacing.xxs,
    borderWidth: designTokens.borderWidth.medium,
    borderColor: designTokens.colors.primary,
  },
  secondaryButtonText: {
    color: designTokens.colors.primary,
    fontSize: mobileFontSizes.lg,
    fontWeight: designTokens.fontWeight.semibold,
  },
});

export const balanceStyles = StyleSheet.create({
  header: {
    flexDirection: layoutConstants.flexDirection.row,
    justifyContent: layoutConstants.justifyContent.spaceBetween,
    alignItems: layoutConstants.alignItems.center,
    padding: designTokens.spacing.lg,
    backgroundColor: designTokens.colors.backgroundPrimary,
    borderBottomWidth: designTokens.borderWidth.thin,
    borderBottomColor: designTokens.colors.borderLight,
  },
  title: {
    fontSize: mobileFontSizes.xl,
    fontWeight: designTokens.fontWeight.bold,
    color: designTokens.colors.textPrimary,
  },
  subtitle: {
    fontSize: mobileFontSizes.xs,
    color: designTokens.colors.textSecondary,
    marginTop: designTokens.spacing.xxs,
  },
  notifyAllButton: {
    flexDirection: layoutConstants.flexDirection.row,
    alignItems: layoutConstants.alignItems.center,
    backgroundColor: designTokens.colors.primary,
    paddingVertical: designTokens.spacing.sm + designTokens.spacing.xxs,
    paddingHorizontal: designTokens.spacing.lg,
    borderRadius: designTokens.borderRadius.md,
    gap: designTokens.spacing.sm,
    ...designTokens.shadows.sm,
  },
  notifyAllButtonText: {
    color: designTokens.colors.white,
    fontSize: mobileFontSizes.sm,
    fontWeight: designTokens.fontWeight.semibold,
  },
  listContainer: { padding: designTokens.spacing.lg },
  card: {
    backgroundColor: designTokens.colors.backgroundPrimary,
    borderRadius: designTokens.borderRadius.lg,
    padding: designTokens.spacing.lg,
    marginBottom: designTokens.spacing.md,
    ...designTokens.shadows.sm,
  },
  cardHeader: {
    flexDirection: layoutConstants.flexDirection.row,
    justifyContent: layoutConstants.justifyContent.spaceBetween,
    alignItems: layoutConstants.alignItems.center,
    marginBottom: designTokens.spacing.lg,
  },
  memberInfo: {
    flexDirection: layoutConstants.flexDirection.row,
    alignItems: layoutConstants.alignItems.center,
    gap: designTokens.spacing.md,
    flex: FLEX.ONE,
  },
  avatar: {
    width: designTokens.touchTarget.minimum,
    height: designTokens.touchTarget.minimum,
    borderRadius: designTokens.touchTarget.minimum / MATH.HALF,
    justifyContent: layoutConstants.justifyContent.center,
    alignItems: layoutConstants.alignItems.center,
  },
  avatarText: {
    color: designTokens.colors.white,
    fontSize: mobileFontSizes.xl,
    fontWeight: designTokens.fontWeight.bold,
  },
  memberTextInfo: { flex: FLEX.ONE },
  name: {
    fontSize: mobileFontSizes.lg,
    fontWeight: designTokens.fontWeight.semibold,
    color: designTokens.colors.textPrimary,
    marginBottom: designTokens.spacing.xxs,
  },
  email: { fontSize: mobileFontSizes.xs, color: designTokens.colors.textSecondary },
  notifyButton: { padding: designTokens.spacing.sm },
  details: { gap: designTokens.spacing.sm + designTokens.spacing.xxs },
  row: {
    flexDirection: layoutConstants.flexDirection.row,
    justifyContent: layoutConstants.justifyContent.spaceBetween,
    alignItems: layoutConstants.alignItems.center,
  },
  label: { fontSize: mobileFontSizes.sm, color: designTokens.colors.textSecondary },
  value: {
    fontSize: mobileFontSizes.md,
    fontWeight: designTokens.fontWeight.semibold,
    color: designTokens.colors.textPrimary,
  },
  totalRow: {
    marginTop: designTokens.spacing.sm,
    paddingTop: designTokens.spacing.md,
    borderTopWidth: designTokens.borderWidth.thin,
    borderTopColor: designTokens.colors.borderLight,
  },
  totalLabel: {
    fontSize: mobileFontSizes.md,
    fontWeight: designTokens.fontWeight.bold,
    color: designTokens.colors.textPrimary,
  },
  totalValue: { fontSize: mobileFontSizes.xl, fontWeight: designTokens.fontWeight.bold },
  overdueNotice: {
    flexDirection: layoutConstants.flexDirection.row,
    alignItems: layoutConstants.alignItems.center,
    backgroundColor: designTokens.colors.errorLight,
    padding: designTokens.spacing.sm + designTokens.spacing.xxs,
    borderRadius: designTokens.borderRadius.md,
    gap: designTokens.spacing.sm,
    marginTop: designTokens.spacing.sm,
    borderLeftWidth: designTokens.borderWidth.thick,
    borderLeftColor: designTokens.colors.error,
  },
  overdueText: {
    fontSize: mobileFontSizes.xs,
    color: designTokens.colors.error,
    fontWeight: designTokens.fontWeight.semibold,
  },
});

export const chargeStyles = StyleSheet.create({
  header: {
    flexDirection: layoutConstants.flexDirection.row,
    justifyContent: layoutConstants.justifyContent.spaceBetween,
    alignItems: layoutConstants.alignItems.center,
    padding: designTokens.spacing.lg,
    backgroundColor: designTokens.colors.backgroundPrimary,
    borderBottomWidth: designTokens.borderWidth.thin,
    borderBottomColor: designTokens.colors.borderLight,
  },
  title: {
    fontSize: mobileFontSizes.xl,
    fontWeight: designTokens.fontWeight.bold,
    color: designTokens.colors.textPrimary,
  },
  subtitle: {
    fontSize: mobileFontSizes.xs,
    color: designTokens.colors.textSecondary,
    marginTop: designTokens.spacing.xxs,
  },
  addButton: {
    flexDirection: layoutConstants.flexDirection.row,
    alignItems: layoutConstants.alignItems.center,
    backgroundColor: designTokens.colors.primary,
    paddingVertical: designTokens.spacing.sm + designTokens.spacing.xxs,
    paddingHorizontal: designTokens.spacing.lg,
    borderRadius: designTokens.borderRadius.md,
    gap: designTokens.spacing.xs + designTokens.spacing.xxs,
    ...designTokens.shadows.sm,
  },
  addButtonText: {
    color: designTokens.colors.white,
    fontSize: mobileFontSizes.sm,
    fontWeight: designTokens.fontWeight.semibold,
  },
  card: {
    backgroundColor: designTokens.colors.backgroundPrimary,
    borderRadius: designTokens.borderRadius.lg,
    padding: designTokens.spacing.lg,
    marginBottom: designTokens.spacing.md,
    ...designTokens.shadows.sm,
    borderLeftWidth: designTokens.borderWidth.heavy,
    borderLeftColor: designTokens.colors.primary,
  },
  cardHeader: {
    flexDirection: layoutConstants.flexDirection.row,
    justifyContent: layoutConstants.justifyContent.spaceBetween,
    alignItems: layoutConstants.alignItems.flexStart,
    marginBottom: designTokens.spacing.md,
  },
  description: {
    fontSize: mobileFontSizes.lg,
    fontWeight: designTokens.fontWeight.semibold,
    color: designTokens.colors.textPrimary,
    flex: FLEX.ONE,
    marginRight: designTokens.spacing.md,
  },
  amount: {
    fontSize: mobileFontSizes['2xl'],
    fontWeight: designTokens.fontWeight.bold,
    color: designTokens.colors.primary,
  },
  details: { gap: designTokens.spacing.sm },
  detailRow: {
    flexDirection: layoutConstants.flexDirection.row,
    alignItems: layoutConstants.alignItems.center,
    gap: designTokens.spacing.sm,
  },
  detailText: { fontSize: mobileFontSizes.sm, color: designTokens.colors.textSecondary },
});

export const emptyStyles = StyleSheet.create({
  container: {
    flex: FLEX.ONE,
    justifyContent: layoutConstants.justifyContent.center,
    alignItems: layoutConstants.alignItems.center,
    paddingVertical: designTokens.spacing['6xl'],
    paddingHorizontal: designTokens.spacing['4xl'],
  },
  text: {
    fontSize: mobileFontSizes.lg,
    fontWeight: designTokens.fontWeight.semibold,
    color: designTokens.colors.textTertiary,
    marginTop: designTokens.spacing.lg,
    textAlign: layoutConstants.textAlign.center,
  },
  subtext: {
    fontSize: mobileFontSizes.sm,
    color: designTokens.colors.borderLight,
    marginTop: designTokens.spacing.sm,
    textAlign: layoutConstants.textAlign.center,
    lineHeight: designTokens.spacing.xl,
  },
});
